[Core]
server_name = "Core1"
server_port = 8701
server_max_conn = 500

[APRS]
server_addr = "aprs.glidernet.org"
server_port = 14580
client_id = 999

[MQTT]
enabled = false
server_addr = "localhost"
server_port = 1883
user_name = "core"
password = "corepassword"
