name: build
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.1.7']
        elixir: ['1.13.0']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test

  system-test:
    runs-on: ubuntu-latest
    name: Run system tests in docker containers
    steps:
      - uses: actions/checkout@v2
      - name: start servers
        run: docker-compose up -d
      - name: execute tests (placholder)
        run: echo "some netcat or tcpreply - it should play traffic from base stations and at the same time get ouput from gat_core"
      - name: stop servers
        run: docker-compose down
